Demo.PL/Models/ErrorViewModel.cs
namespace Demo.PL.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Demo.PL/Models/ItemStockViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Demo.PL.Models
{
    public class ItemStockViewModel
    {
        [Required(ErrorMessage = "This Is Required")]
        public int StoreId { get; set; }

        [Required(ErrorMessage = "This Is Required")]
        public int ItemId { get; set; }

        public int Quantity { get; set; }
    }
}

Demo.PL/Models/ItemViewModel.cs
namespace Demo.PL.Models
{
    public class ItemViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }
}

Demo.PL/Models/StoreViewModel.cs
namespace Demo.PL.Models
{
    public class StoreViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}

Demo.PL/Controllers/HomeController.cs
using Demo.PL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Demo.PL.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Demo.PL/Controllers/ItemController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PL.Controllers
{
	public class ItemController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public ItemController(IUnitOfWork unitOfWork, IMapper mapper)
        {
			_unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public IActionResult Index()
		{
			var items = _unitOfWork.ItemRepository.GetAll();
			var mappedItem = _mapper.Map <IEnumerable<Item>,IEnumerable<ItemViewModel>> (items);

            return View(mappedItem);
		}

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(ItemViewModel itemVM)
        {
            if (ModelState.IsValid)
            {
				var item = _mapper.Map <ItemViewModel, Item> (itemVM);
                _unitOfWork.ItemRepository.Add(item);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            return View(itemVM);
        }

		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id is null)
				return BadRequest();

			var item = _unitOfWork.ItemRepository.GetById(id);
			if (item is null)
				return NotFound();

			var itemVM = _mapper.Map<Item, ItemViewModel>(item);


            return View(itemVM);
		}
		[HttpPost]
		public IActionResult Edit(ItemViewModel itemVM, [FromRoute] int id)
		{
			if (id != itemVM.Id)
				return BadRequest();

			if (ModelState.IsValid)
			{
				var item = _mapper.Map<ItemViewModel, Item>(itemVM);
                _unitOfWork.ItemRepository.Update(item);
				_unitOfWork.Complete();
				return RedirectToAction(nameof(Index));
			}
			return View(itemVM);
		}

		public IActionResult Delete(int? id)
		{
			if (id is null)
				return BadRequest();

			var item = _unitOfWork.ItemRepository.GetById(id);

			if (item is null)
				return NotFound();

			_unitOfWork.ItemRepository.Delete(item);
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}



	}
}

Demo.PL/Controllers/ItemStockController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PL.Controllers
{
	public class ItemStockController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public ItemStockController(IUnitOfWork unitOfWork, IMapper mapper)
        {
			_unitOfWork = unitOfWork;
            _mapper = mapper;
        }

		
		public IActionResult Increase(ItemStockViewModel itemStockVM) 
		{
			ViewBag.Itemes = _unitOfWork.ItemRepository.GetAll();
			ViewBag.Stores = _unitOfWork.StoreRepository.GetAll();

			return View(itemStockVM);
		}
		[HttpPost]
		public IActionResult Increase(int itemId, int storeId, int quantity) 
		{
			var itemStock = _unitOfWork.ItemStockRepository.GetAll();
			var stock = itemStock.FirstOrDefault(s => s.ItemId  == itemId && s.StoreId == storeId);

			if (stock != null)
			{
				stock.Quantity += quantity;
				_unitOfWork.ItemStockRepository.Update(stock);
				_unitOfWork.Complete();
				
				var mappedStock = _mapper.Map<ItemStock, ItemStockViewModel>(stock);
				return RedirectToAction("Increase", mappedStock);
			}
			else
			{
				ItemStock newItemStock = new ItemStock
				{
					ItemId = itemId,
					StoreId = storeId,
					Quantity = quantity
				};
				_unitOfWork.ItemStockRepository.Add(newItemStock);
				_unitOfWork.Complete();

                var mappedStock = _mapper.Map<ItemStock, ItemStockViewModel>(newItemStock);
                return RedirectToAction("Increase", mappedStock);
            }

        }


        [HttpGet]
        public  IActionResult GetQuantity(int storeId, int itemId)
        {
            var itemStock = _unitOfWork.ItemStockRepository.GetAll();
            var stock = itemStock.FirstOrDefault(s => s.ItemId == itemId && s.StoreId == storeId);

            if (stock != null)
            {
                return Json(new { quantity = stock.Quantity });
            }
            else
            {
                return Json(new { quantity = 0 });
            }
        }



    }
}

Demo.PL/Controllers/StoreController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Demo.PL.Controllers
{
	public class StoreController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public StoreController(IUnitOfWork unitOfWork, IMapper mapper)
		{
			_unitOfWork = unitOfWork;
            _mapper = mapper;
        }

		public IActionResult Index()
		{
			var stores = _unitOfWork.StoreRepository.GetAll();
			var mappedStores = _mapper.Map<IEnumerable<Store>, IEnumerable<StoreViewModel>>(stores);

            return View(mappedStores);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Add(StoreViewModel storeVM)
		{
			if(ModelState.IsValid)
			{
				var store = _mapper.Map<StoreViewModel, Store>(storeVM);
                _unitOfWork.StoreRepository.Add(store);
				_unitOfWork.Complete();
				return RedirectToAction(nameof(Index));
			}
			return View(storeVM);
		}

		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id is null)
				return BadRequest();

			var store = _unitOfWork.StoreRepository.GetById(id);
			if(store is null)
				return NotFound();

			var storeVM = _mapper.Map<Store, StoreViewModel>(store);


            return View(storeVM);
		}
		[HttpPost]
		public IActionResult Edit(StoreViewModel storeVM, [FromRoute] int id)
		{
			if(id != storeVM.Id)
				return BadRequest();

			if (ModelState.IsValid)
			{
				var store = _mapper.Map<StoreViewModel, Store>(storeVM);
                _unitOfWork.StoreRepository.Update(store);
				_unitOfWork.Complete();
				return RedirectToAction(nameof(Index));
			}
			return View(storeVM);
		}

		public IActionResult Delete(int? id)
		{
			if (id is null)
				return BadRequest();

			var store = _unitOfWork.StoreRepository.GetById(id);

			if (store is null)
				return NotFound();

			_unitOfWork.StoreRepository.Delete(store);
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}

	}
}

Demo.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.PL/Views/Item/Add.cshtml
@model ItemViewModel
@{
	ViewData["Title"] = "Add";
}

<div class="row">
	<div class="col-6">
		<form asp-action="Add" asp-controller="Item">
			<div class="form-group">
				<label asp-for="@Model.Name" class="col-form-label"></label>
				<input asp-for="@Model.Name" class="form-control" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="@Model.Price" class="col-form-label"></label>
				<input asp-for="@Model.Price" class="form-control" />
				<span asp-validation-for="@Model.Price" class="text-danger"></span>
			</div>
			<br />
			<input type="submit" value="Add" class="btn btn-primary" />
			<a asp-action="Index" class="btn btn-light">Back To List</a>
		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Demo.PL/Views/Item/Edit.cshtml
@model ItemViewModel
@{
	ViewData["Title"] = "Edit";
}

<h1>Edit @Model.Name</h1>

<div class="row">
	<div class="col-6">
		<form asp-action="Edit" asp-controller="Item">
			<div class="form-group">
				<label asp-for="@Model.Name" class="col-form-label"></label>
				<input asp-for="@Model.Name" class="form-control" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="@Model.Price" class="col-form-label"></label>
				<input asp-for="@Model.Price" class="form-control" />
				<span asp-validation-for="@Model.Price" class="text-danger"></span>
			</div>
			<br />
			<input type="submit" value="Save" class="btn btn-primary" />
			<a asp-action="Index" class="btn btn-light">Back To List</a>
		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Demo.PL/Views/Item/Index.cshtml
@model IEnumerable<ItemViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1>All Items</h1>
<br />
<a asp-action="Add" class="btn btn-primary">Create New Item</a>
<br />
<br />


@if(Model?.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(x => x.Name)</th>
                <th scope="col">@Html.DisplayNameFor(x => x.Price)</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>
                        <a class="btn btn-warning" asp-controller="Item" asp-action="Edit" asp-route-id="@item.Id">
                            <i class="fas fa-edit"></i>Edit
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Item" asp-action="Delete" asp-route-id="@item.Id">
                            <i class="fas fa-trash"></i>Delete
                        </a>
                    </td>
                </tr>
            }
            
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <h3>No Items Found !!! </h3>
    </div>
}

Demo.PL/Views/ItemStock/Increase.cshtml
@model ItemStockViewModel
@{
    ViewData["Title"] = "Increase";

    var Items = new SelectList(ViewBag.Itemes, "Id", "Name");
    var Stores = new SelectList(ViewBag.Stores, "Id", "Name");

}

<h1>Increase</h1>

<div class="row">
    <div class="col-6">
        <form asp-action="Increase" method="post">

            <div class="form-group">
                <label class="col-form-label">Item</label>
                <select id="itemDropdown" asp-for="@Model.ItemId" asp-items="Items" class="form-control">
                    <option>--- Select Department ---</option>
                </select>
                <span asp-validation-for="@Model.ItemId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="col-form-label">Store</label>
                <select id="storeDropdown" asp-for="@Model.StoreId" asp-items="Stores" class="form-control">
                    <option>--- Select Department ---</option>
                </select>
                <span asp-validation-for="@Model.StoreId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="col-form-label">Current Quantity</label>
                <span id="currentQuantity" >@Model.Quantity</span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Quantity" class="col-form-label"></label>
                <input asp-for="@Model.Quantity" value="@Model.Quantity" type="number" class="form-control" />
                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
            </div>

            <br />
            <input type="submit" value="Add" class="btn btn-primary" />

        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            function fetchQuantity() {
                var storeId = $("#storeDropdown").val();
                var itemId = $("#itemDropdown").val();

                if (storeId && itemId) {
                    $.ajax({
                        url: '@Url.Action("GetQuantity", "ItemStock")',
                        type: 'GET',
                        data: { storeId: storeId, itemId: itemId },
                        success: function (data) {
                            $("#currentQuantity").text(data.quantity);
                        },
                        error: function () {
                            $("#currentQuantity").text("Error fetching quantity");
                        }
                    });
                } else {
                    $("#currentQuantity").text("-");
                }
            }

            $("#storeDropdown, #itemDropdown").change(fetchQuantity);
        });
    </script>
    }

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ItemStock" asp-action="Increase">ItemStock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo.PL/Views/Store/Add.cshtml
@model StoreViewModel
@{
    ViewData["Title"] = "Add";
}

<div class="row">
	<div class="col-6">
		<form asp-action="Add" asp-controller="Store">
			<div class="form-group">
				<label asp-for="@Model.Name" class="col-form-label"></label>
				<input asp-for="@Model.Name" class="form-control" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="@Model.Location" class="col-form-label"></label>
				<input asp-for="@Model.Location" class="form-control" />
				<span asp-validation-for="@Model.Location" class="text-danger"></span>
			</div>
			<br />
			<input type="submit" value="Add" class="btn btn-primary" />
			<a asp-action="Index" class="btn btn-light">Back To List</a>
		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Demo.PL/Views/Store/Edit.cshtml
@model StoreViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.Name</h1>

<div class="row">
	<div class="col-6">
		<form asp-action="Edit" asp-controller="Store">
			<div class="form-group">
				<label asp-for="@Model.Name" class="col-form-label"></label>
				<input asp-for="@Model.Name" class="form-control" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="@Model.Location" class="col-form-label"></label>
				<input asp-for="@Model.Location" class="form-control" />
				<span asp-validation-for="@Model.Location" class="text-danger"></span>
			</div>
			<br />
			<input type="submit" value="Save" class="btn btn-primary" />
			<a asp-action="Index" class="btn btn-light">Back To List</a>
		</form>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Demo.PL/Views/Store/Index.cshtml
@model IEnumerable<StoreViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1>All Stores</h1>
<br />
<a asp-action="Add" class="btn btn-primary">Create New Store</a>
<br />
<br />


@if(Model?.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(x => x.Name)</th>
                <th scope="col">@Html.DisplayNameFor(x => x.Location)</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Location</td>
                    <td>
                        <a class="btn btn-warning" asp-controller="Store" asp-action="Edit" asp-route-id="@item.Id">
                            <i class="fas fa-edit"></i>Edit
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Store" asp-action="Delete" asp-route-id="@item.Id">
                            <i class="fas fa-trash"></i>Delete
                        </a>
                    </td>
                </tr>
            }
            
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <h3>No Stores Found !!! </h3>
    </div>
}